<?php
/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace Chargebee\Telemetry;

/** Result passed to {@see TelemetryAdapter::onRequestEnd}. */
final class RequestTelemetryResult
{
    /**
     * @param array<string, string|int> $endAttributes
     */
    public function __construct(
        public readonly int $httpStatusCode,
        public readonly int $durationMs,
        public readonly ?RequestTelemetryError $error,
        public readonly array $endAttributes,
    ) {
    }
}
