<?php
/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace Chargebee\Telemetry;

/** Context passed to {@see TelemetryAdapter::onRequestStart}. */
final class RequestTelemetryContext
{
    /**
     * @param array<string, string> $startAttributes
     */
    public function __construct(
        public readonly string $spanName,
        public readonly string $resource,
        public readonly string $operation,
        public readonly string $httpMethod,
        public readonly string $httpUrl,
        public readonly string $serverAddress,
        public readonly string $chargebeeSite,
        public readonly string $chargebeeApiVersion,
        public readonly string $sdkName,
        public readonly string $sdkVersion,
        public readonly array $startAttributes,
    ) {
    }
}
