<?php
/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace Chargebee\Telemetry;

/** Error details attached to {@see RequestTelemetryResult} on failed requests. */
final class RequestTelemetryError
{
    public function __construct(
        public readonly string $message,
        public readonly ?string $chargebeeErrorCode = null,
        public readonly ?string $chargebeeApiErrorType = null,
        public readonly ?string $chargebeeErrorParam = null,
    ) {
    }
}
