<?php
/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace Chargebee\Telemetry;

/**
 * Optional telemetry adapter for observability integrations (e.g. OpenTelemetry).
 *
 * When not configured, the SDK skips all telemetry work — zero overhead. The SDK stores the
 * adapter by reference and never clones or deep-copies it.
 *
 * Implementations may inject W3C trace context headers (traceparent, tracestate)
 * into $requestHeaders during onRequestStart.
 */
interface TelemetryAdapter
{
    /**
     * Called once per SDK API call before the request is sent (including before retries).
     *
     * @param array<string, string> $requestHeaders mutable headers map for trace propagation
     * @return mixed opaque handle passed back to onRequestEnd, or null
     */
    public function onRequestStart(RequestTelemetryContext $context, array &$requestHeaders): mixed;

    /**
     * Called once per SDK API call after the final response or terminal failure.
     */
    public function onRequestEnd(mixed $handle, RequestTelemetryResult $result): void;
}
