<?php
/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace Chargebee\Telemetry;

use Chargebee\Exceptions\APIError;

/** Helpers for building standardized Chargebee telemetry context and results. */
final class TelemetrySupport
{
    private function __construct()
    {
    }

    public static function buildSpanName(string $resource, string $operation): string
    {
        return TelemetryAttributeKeys::TELEMETRY_SPAN_NAME_PREFIX . '.' . $resource . '.' . $operation;
    }

    public static function resolveChargebeeApiVersion(string $apiPath): string
    {
        return $apiPath === '/api/v1' ? 'v1' : 'v2';
    }

    /**
     * @param array<string, string> $requestHeaders
     * @return array<string, string>
     */
    public static function buildRequestStartSpanAttributes(
        string $resource,
        string $operation,
        string $httpMethod,
        string $httpUrl,
        string $serverAddress,
        string $chargebeeSite,
        string $chargebeeApiVersion,
        string $sdkVersion,
        array $requestHeaders = [],
    ): array {
        return array_merge([
            TelemetryAttributeKeys::URL_FULL => $httpUrl,
            TelemetryAttributeKeys::HTTP_REQUEST_METHOD => $httpMethod,
            TelemetryAttributeKeys::SERVER_ADDRESS => $serverAddress,
            TelemetryAttributeKeys::CHARGEBEE_SITE => $chargebeeSite,
            TelemetryAttributeKeys::CHARGEBEE_API_VERSION => $chargebeeApiVersion,
            TelemetryAttributeKeys::CHARGEBEE_RESOURCE => $resource,
            TelemetryAttributeKeys::CHARGEBEE_OPERATION => $operation,
            TelemetryAttributeKeys::CHARGEBEE_SDK_NAME => TelemetryAttributeKeys::SDK_NAME,
            TelemetryAttributeKeys::CHARGEBEE_SDK_VERSION => $sdkVersion,
        ], self::buildRequestHeaderSpanAttributes($requestHeaders));
    }

    /**
     * Promotes chargebee-* request headers to http.request.header.* attributes; excludes the chargebee-request-origin-* PII family.
     *
     * @param array<string, string> $requestHeaders
     * @return array<string, string>
     */
    public static function buildRequestHeaderSpanAttributes(array $requestHeaders): array
    {
        $attributes = [];
        foreach ($requestHeaders as $name => $value) {
            if ($value === null) {
                continue;
            }
            $lowerName = strtolower((string) $name);
            if (
                !str_starts_with($lowerName, TelemetryAttributeKeys::CHARGEBEE_TELEMETRY_HEADER_PREFIX)
                || str_starts_with($lowerName, TelemetryAttributeKeys::CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX)
            ) {
                continue;
            }
            $attributes[TelemetryAttributeKeys::HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX . $lowerName] = (string) $value;
        }

        return $attributes;
    }

    /**
     * @return array<string, string|int>
     */
    public static function buildRequestEndSpanAttributes(
        int $httpStatusCode,
        ?RequestTelemetryError $error,
    ): array {
        $attributes = [
            TelemetryAttributeKeys::HTTP_RESPONSE_STATUS_CODE => $httpStatusCode,
        ];

        if ($error !== null) {
            if ($error->chargebeeApiErrorType !== null) {
                $attributes[TelemetryAttributeKeys::ERROR_TYPE] = $error->chargebeeApiErrorType;
                $attributes[TelemetryAttributeKeys::CHARGEBEE_ERROR_TYPE] = $error->chargebeeApiErrorType;
            }

            if ($error->chargebeeErrorCode !== null) {
                $attributes[TelemetryAttributeKeys::CHARGEBEE_ERROR_CODE] = $error->chargebeeErrorCode;
            }
            if ($error->chargebeeErrorParam !== null) {
                $attributes[TelemetryAttributeKeys::CHARGEBEE_ERROR_PARAM] = $error->chargebeeErrorParam;
            }
        }

        return $attributes;
    }

    /**
     * @param array<string, string> $requestHeaders
     */
    public static function buildRequestTelemetryContext(
        string $resource,
        string $operation,
        string $httpMethod,
        string $httpUrl,
        string $serverAddress,
        string $chargebeeSite,
        string $chargebeeApiVersion,
        string $sdkVersion,
        array $requestHeaders = [],
    ): RequestTelemetryContext {
        return new RequestTelemetryContext(
            self::buildSpanName($resource, $operation),
            $resource,
            $operation,
            $httpMethod,
            $httpUrl,
            $serverAddress,
            $chargebeeSite,
            $chargebeeApiVersion,
            TelemetryAttributeKeys::SDK_NAME,
            $sdkVersion,
            self::buildRequestStartSpanAttributes(
                $resource,
                $operation,
                $httpMethod,
                $httpUrl,
                $serverAddress,
                $chargebeeSite,
                $chargebeeApiVersion,
                $sdkVersion,
                $requestHeaders,
            ),
        );
    }

    public static function buildRequestTelemetryResult(
        int $httpStatusCode,
        int $durationMs,
        ?RequestTelemetryError $error,
    ): RequestTelemetryResult {
        return new RequestTelemetryResult(
            $httpStatusCode,
            $durationMs,
            $error,
            self::buildRequestEndSpanAttributes($httpStatusCode, $error),
        );
    }

    public static function extractRequestTelemetryError(?\Throwable $err): ?RequestTelemetryError
    {
        if ($err === null) {
            return null;
        }

        $message = $err->getMessage() !== '' ? $err->getMessage() : 'Chargebee API request failed';

        if ($err instanceof APIError) {
            return new RequestTelemetryError(
                $message,
                $err->getApiErrorCode(),
                $err->getType(),
                $err->getParam(),
            );
        }

        return new RequestTelemetryError($message);
    }

    public static function extractHttpStatusCode(?\Throwable $err): ?int
    {
        if ($err instanceof APIError) {
            return $err->getHttpStatusCode();
        }

        return null;
    }
}
