<?php
/*
 * This file is auto-generated by Chargebee.
 * For more information on how to make changes to this file, please see the README.
 * Reach out to dx@chargebee.com for any questions.
 * Copyright 2026 Chargebee Inc.
 */

namespace Chargebee\Telemetry;

/**
 * Span attribute keys shared across Chargebee SDKs.
 */
final class TelemetryAttributeKeys
{
    public const SDK_NAME = 'chargebee-php';
    public const TELEMETRY_SPAN_NAME_PREFIX = 'chargebee';

    public const HTTP_REQUEST_HEADER_ATTRIBUTE_PREFIX = 'http.request.header.';
    public const CHARGEBEE_TELEMETRY_HEADER_PREFIX = 'chargebee-';
    public const CHARGEBEE_TELEMETRY_HEADER_EXCLUDE_PREFIX = 'chargebee-request-origin-';

    public const URL_FULL = 'url.full';
    public const HTTP_REQUEST_METHOD = 'http.request.method';
    public const HTTP_RESPONSE_STATUS_CODE = 'http.response.status_code';
    public const SERVER_ADDRESS = 'server.address';
    public const ERROR_TYPE = 'error.type';
    public const CHARGEBEE_SITE = 'chargebee.site';
    public const CHARGEBEE_API_VERSION = 'chargebee.api_version';
    public const CHARGEBEE_RESOURCE = 'chargebee.resource';
    public const CHARGEBEE_OPERATION = 'chargebee.operation';
    public const CHARGEBEE_SDK_NAME = 'chargebee.sdk.name';
    public const CHARGEBEE_SDK_VERSION = 'chargebee.sdk.version';
    public const CHARGEBEE_ERROR_CODE = 'chargebee.error.code';
    public const CHARGEBEE_ERROR_TYPE = 'chargebee.error.type';
    public const CHARGEBEE_ERROR_PARAM = 'chargebee.error.param';

    private function __construct()
    {
    }
}
