blank_issues_enabled: false
contact_links:
  - name: Chargebee support
    url: https://support.chargebee.com/
    about: |
      Github issues are not an official support channel for Chargebee. If you have an urgent request we suggest you contact us through an official channel: support@chargebee.com or  https://support.chargebee.com/