name: Feature Request
description: Request a New Feature for the project.
labels:
  - Feature Request

body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does your feature request address?
      description: Please provide a clear and concise description of the problem you'd like to solve. For example, "I'm frequently frustrated when..."

  - type: textarea
    id: solution
    attributes:
      label: Describe the desired solution
      description: Please provide a clear and concise description of the solution you would like to see implemented.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you may have thought about in relation to this problem.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Feel free to include any other relevant information or context regarding your feature request.

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit your feature request!
